<?php
/**
 * @see \Payever\Payever\Block\Adminhtml\System\Config\Credentials
 */
?>
<script type="text/javascript">
require(['prototype'], function() {
//<![CDATA[
    function setUpCredentials() {
        var messagesContainer = $('credentials_result');
        $(messagesContainer).update('');

        new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
            method:     'get',
            onSuccess: function(response) {

                var isSuccess = false;
                var result = '<?php echo $block->escapeHtml(__('Error during Set up Demo Keys.')) ?>';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    messagesContainer.removeClassName('hidden');
                    if (response.result == 'success') {
                        messagesContainer.addClassName('success').addClassName('message-success')
                        isSuccess = true;
                        window.synchronize();
                    } else {
                        messagesContainer.addClassName('error').addClassName('message-error')
                    }
                } catch (e) {
                    messagesContainer.removeClassName('hidden').addClassName('error').addClassName('message-error')
                }

                messagesContainer.update(result);

                if (!isSuccess) {
                    setTimeout(function() {
                        location.reload();
                    },2000);
                }
            }
        });
    }

    window.setUpCredentials = setUpCredentials;
//]]>

});
</script>
<div class="actions actions-credentials">
    <button onclick="javascript:setUpCredentials(); return false;"
            <?php if ($block->getDisabled()) :
?>disabled<?php
            endif; ?>
            class="action-credentials" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>

    <div id="credentials_result" class="message-validation hidden message"></div>
</div>
